version: '3.8'

services:
    node-app:
        image: node:20
        container_name: psicologo_carlosmolero_web_dev
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        command: sh -c "npm i -g pnpm && pnpm i && pnpm run dev"
