// Generated by Wrangler on Sat Feb 08 2025 00:11:47 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	CONTENTFUL_CDA_ACCESS_TOKEN: string;
	CONTENTFUL_CMA_ACCESS_TOKEN: string;
	CONTENTFUL_SPACE_ID: string;
}
